baseURL: "https://darcien.dev/"
title: "A blog by Yosua Ian Sebastian"
paginate: 20
theme: PaperMod

enableRobotsTXT: true
buildDrafts: false
buildFuture: false
buildExpired: false

# googleAnalytics: UA-123-45

# minify:
#   disableXML: true
#   minifyOutput: true

outputs:
  home:
    - HTML
    - RSS
    - JSON # JSON is needed for search

params:
  env: production # to enable google analytics, opengraph, twitter-cards and schema.
  title: "A blog by Yosua Ian Sebastian"
  description: "Personal blog by Yosua Ian Sebastian."
  keywords: [Blog]
  author: Yosua
  # author: ["Me", "You"] # multiple authors

  # images: ["<link or path of image for opengraph, twitter-cards>"]
  # images: ["img/cresent-moon.png"]

  # https://gohugo.io/functions/format/#hugo-date-and-time-templating-reference
  DateFormat: "2006-01-02"
  # DateFormat: "January 2, 2006"

  defaultTheme: auto # dark, light
  disableThemeToggle: false

  ShowReadingTime: true
  ShowWordCount: true

  # controls share buttons in post page
  ShowShareButtons: false

  # next/prev link in each post
  ShowPostNavLinks: true

  # breadcrumbs on top of each post title
  ShowBreadCrumbs: false
  ShowCodeCopyButtons: true
  ShowRssButtonInSectionTermList: true
  UseHugoToc: true
  disableSpecial1stPost: false
  disableScrollToTop: false
  comments: false
  hidemeta: false
  hideSummary: false

  # Hide toc by default but make them initially open
  showtoc: false
  tocopen: true

  assets:
    # Consider enabling this or use chroma from hugo if later write post with code
    disableHLJS: true # to disable highlight.js
    # https://gohugo.io/hugo-pipes/fingerprint/
    # disableFingerprinting: true
    favicon: "whale72.png"
    favicon16x16: "whale16.png"
    favicon32x32: "whale32.png"
    apple_touch_icon: "whale57.png"
    # safari_pinned_tab: "<link / abs url>"

  label:
    text: "Home"
    icon: /whale72.png
    iconHeight: 28

  # home-info mode - this is what we use
  homeInfoParams:
    Title: "Halo \U0001F44B"
    Content: Personal blog by Yosua Ian Sebastian.

  # profile-mode - not used
  # https://github.com/adityatelange/hugo-PaperMod/wiki/Features#profile-mode
  profileMode:
    enabled: false # needs to be explicitly set
    title: ExampleSite
    subtitle: "This is subtitle"
    imageUrl: "#"
    imageWidth: 120
    imageHeight: 120
    imageTitle: my image
    buttons:
      - name: Posts
        url: posts
      - name: Tags
        url: tags

  socialIcons:
    - name: twitter
      url: "https://twitter.com/darcien_"
    - name: github
      url: "https://github.com/darcien"
    - name: ycombinator
      url: "https://news.ycombinator.com/user?id=darcien"
    - name: email
      url: "mailto:hello@darcien.me"
    - name: steam
      url: "https://steamcommunity.com/id/darcien"
    - name: strava
      url: "https://www.strava.com/athletes/39346424"

  # analytics:
  #   google:
  #     SiteVerificationTag: "XYZabc"
  #   bing:
  #     SiteVerificationTag: "XYZabc"
  #   yandex:
  #     SiteVerificationTag: "XYZabc"

  # cover:
  #   image: ""
  #   hidden: true # hide everywhere but not in structured data
  #   hiddenInList: true # hide on list pages and home
  #   hiddenInSingle: true # hide on single page

  # editPost:
  #   URL: "https://github.com/<path_to_repo>/content"
  #   Text: "Suggest Changes" # edit text
  #   appendFilePath: true # to append file path to Edit link

  # for search
  # https://fusejs.io/api/options.html
  fuseOpts:
    isCaseSensitive: false
    shouldSort: true
    location: 0
    distance: 1000
    threshold: 0.4
    minMatchCharLength: 0
    keys: ["title", "permalink", "summary", "content"]
menu:
  main:
    - identifier: about
      name: about
      url: /about
      weight: 10
    - name: search
      url: search
      weight: 15
    - identifier: tags
      name: tags
      url: /tags/
      weight: 20
    - identifier: source
      name: source
      url: https://github.com/darcien/darcien.dev
      weight: 30
# Read: https://github.com/adityatelange/hugo-PaperMod/wiki/FAQs#using-hugos-syntax-highlighter-chroma
pygmentsUseClasses: true
markup:
  highlight:
    noClasses: false
    # anchorLineNos: true
    # codeFences: true
    # guessSyntax: true
    # lineNos: true
    # style: monokai
