baseURL: "https://darcien.dev/"
title: "A blog by Yosua Ian Sebastian"
paginate: 5
theme: PaperMod

enableRobotsTXT: true
buildDrafts: false
buildFuture: false
buildExpired: false

# googleAnalytics: UA-123-45

# minify:
#   disableXML: true
#   minifyOutput: true

outputs:
  home:
    - HTML
    - RSS
    - JSON # JSON is needed for search

params:
  env: production # to enable google analytics, opengraph, twitter-cards and schema.
  title: "A blog by Yosua Ian Sebastian"
  description: "Personal blog by Yosua Ian Sebastian."
  keywords: [Blog]
  author: Yosua
  # author: ["Me", "You"] # multiple authors

  # images: ["<link or path of image for opengraph, twitter-cards>"]
  # images: ["img/cresent-moon.png"]

  # https://gohugo.io/functions/format/#hugo-date-and-time-templating-reference
  DateFormat: "2006-01-02"
  # DateFormat: "January 2, 2006"

  defaultTheme: auto # dark, light
  disableThemeToggle: false

  ShowReadingTime: true
  ShowWordCount: true

  # controls share buttons in post page
  ShowShareButtons: false

  # next/prev link in each post
  ShowPostNavLinks: true

  # breadcrumbs on top of each post title
  ShowBreadCrumbs: false
  ShowCodeCopyButtons: true
  ShowRssButtonInSectionTermList: true
  UseHugoToc: true
  disableSpecial1stPost: false
  disableScrollToTop: false
  comments: false
  hidemeta: false
  hideSummary: false

  # Hide toc by default but make them initially open
  showtoc: false
  tocopen: true

  assets:
    # Consider enabling this or use chroma from hugo if later write post with code
    disableHLJS: true # to disable highlight.js
    # https://gohugo.io/hugo-pipes/fingerprint/
    # disableFingerprinting: true
    # Favicon no longer configured here,
    # see favicons.html instead.
    # favicon: "whale72.png"
    # favicon16x16: "whale16.png"
    # favicon32x32: "whale32.png"
    # apple_touch_icon: "whale57.png"
    # safari_pinned_tab: "<link / abs url>"

  label:
    text: "Yosua Ian Sebastian"
    icon: /whale_goth.svg
    iconHeight: 28

  # home-info mode - this is what we use
  homeInfoParams:
    Title: "👋 Halo"
    Content: "I write code for living, go cycling on free time, and listen to Japanese songs.\n\nSometimes I write about those here."

  # profile-mode - not used
  # https://github.com/adityatelange/hugo-PaperMod/wiki/Features#profile-mode
  profileMode:
    enabled: false # needs to be explicitly set
    title: ExampleSite
    subtitle: "This is subtitle"
    imageUrl: "#"
    imageWidth: 120
    imageHeight: 120
    imageTitle: my image
    buttons:
      - name: Posts
        url: posts
      - name: Tags
        url: tags

  socialIcons:
    - name: twitter
      url: "https://twitter.com/darcien_"
    - name: github
      url: "https://github.com/darcien"
    - name: strava
      url: "https://www.strava.com/athletes/39346424"
    - name: email
      url: "mailto:hello@darcien.me"

  # analytics:
  #   google:
  #     SiteVerificationTag: "XYZabc"
  #   bing:
  #     SiteVerificationTag: "XYZabc"
  #   yandex:
  #     SiteVerificationTag: "XYZabc"

  # cover:
  #   image: ""
  #   hidden: true # hide everywhere but not in structured data
  #   hiddenInList: true # hide on list pages and home
  #   hiddenInSingle: true # hide on single page

  # editPost:
  #   URL: "https://github.com/<path_to_repo>/content"
  #   Text: "Suggest Changes" # edit text
  #   appendFilePath: true # to append file path to Edit link

  # for search
  # https://fusejs.io/api/options.html
  fuseOpts:
    isCaseSensitive: false
    ignoreLocation: true
    shouldSort: true
    threshold: 0.3
    minMatchCharLength: 2
    keys: ["title", "permalink", "summary", "content"]
menu:
  main:
    - identifier: now
      name: now
      url: /now
      weight: 1
    - identifier: about
      name: about
      url: /about
      weight: 10
    - identifier: uses
      name: uses
      url: /uses
      weight: 30
    - identifier: archive
      name: archive
      url: /archive
      weight: 80
    - identifier: tags
      name: tags
      url: /tags
      weight: 90
    - name: search
      url: /search
      weight: 100
    - name: status
      url: https://status.darcien.dev/
      weight: 200
    # A proper RSS client should be able to pick up RSS from homepage
    # - identifier: rss
    #   name: rss
    #   url: /index.xml
    #   weight: 30
    # Hide source for now, not very useful and takes up spaces
    # - identifier: source
    #   name: source
    #   url: https://github.com/darcien/blog
    #   weight: 40
# Read: https://github.com/adityatelange/hugo-PaperMod/wiki/FAQs#using-hugos-syntax-highlighter-chroma
pygmentsUseClasses: true
markup:
  highlight:
    noClasses: false
    # anchorLineNos: true
    # codeFences: true
    # guessSyntax: true
    # lineNos: true
    # style: monokai
