baseURL = "https://darcien.dev/"
languageCode = "en-us"
title = "A Personal Playground"
theme = "terminal"
paginate = 5

[params]
  # dir name of your blog content (default is `content/posts`)
  contentTypeName = "p"

  # ["orange", "blue", "red", "green", "pink"]
  themeColor = "green"

  # if you set this to 0, only submenu trigger will be visible
  showMenuItems = 4

  # show selector to switch language
  showLanguageSelector = false

  # set theme to full screen width
  fullWidthTheme = false

  # center theme with default width
  centerTheme = true

  # set a custom favicon (default is a `themeColor` square)
  # favicon = "favicon.ico"

  # set all headings to their default size (depending on browser settings)
  # it's set to `true` by default
  # oneHeadingSize = false

[params.twitter]
  # set Twitter handles for Twitter cards
  # see https://developer.twitter.com/en/docs/tweets/optimize-with-cards/guides/getting-started#card-and-content-attribution
  # do not include @
  creator = "darcien_"
  site = ""

[languages]
  [languages.en]
    languageName = "English"
    title = "Darcien's Personal Garden"
    subtitle = "Powered by ☕️"
    owner = ""
    keywords = ""
    copyright = "" # modified in themes/terminal/layouts/partials/footer.html
    menuMore = "Show more"
    readMore = "Read more"
    readOtherPosts = "Read other posts"

    [languages.en.params.logo]
      logoText = "darcien.dev"
      logoHomeLink = "/"

    [languages.en.menu]
      [[languages.en.menu.main]]
        identifier = "about"
        name = "About"
        url = "/about"
      [[languages.en.menu.main]]
        identifier = "coffee"
        name = "Coffee"
        url = "/coffee"
      [[languages.en.menu.main]]
        identifier = "playlist"
        name = "Playlist"
        url = "/playlist"
      [[languages.en.menu.main]]
        identifier = "shed"
        name = "Shed"
        url = "/shed"
